### ISSUE TITLE
Paper compatibility ?

### ISSUE THREAD

**Issue by Diamax10** [btk5h/skript-db#18]
Hello,

It seems that the addon is not compatible with Paper(Spigot), here is the error :

>`[20:20:32 INFO]: [skript-db] Enabling skript-db v0.2.1
[20:20:32 ERROR]: Error occurred while enabling skript-db v0.2.1 (Is it up to date?)
java.lang.NoClassDefFoundError: com/zaxxer/hikari/HikariDataSource
at com.btk5h.skriptdb.skript.ExprDataSource.<clinit>(ExprDataSource.java:33) ~[?:?]
at java.lang.Class.forName0(Native Method) ~[?:1.8.0_212]
at java.lang.Class.forName(Class.java:348) ~[?:1.8.0_212]
at ch.njol.skript.SkriptAddon.loadClasses(SkriptAddon.java:108) ~[?:?]
at com.btk5h.skriptdb.SkriptDB.onEnable(SkriptDB.java:66) ~[?:?]
at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[Paper-1.12.2-b1616.jar:git-Paper-1616]
at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:316) ~[Paper-1.12.2-b1616.jar:git-Paper-1616]
at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) ~[Paper-1.12.2-b1616.jar:git-Paper-1616]
at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:395) ~[Paper-1.12.2-b1616.jar:git-Paper-1616]
at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:344) ~[Paper-1.12.2-b1616.jar:git-Paper-1616]
at net.minecraft.server.v1_12_R1.MinecraftServer.t(MinecraftServer.java:442) ~[Paper-1.12.2-b1616.jar:git-Paper-1616]
at net.minecraft.server.v1_12_R1.MinecraftServer.l(MinecraftServer.java:403) ~[Paper-1.12.2-b1616.jar:git-Paper-1616]
at net.minecraft.server.v1_12_R1.MinecraftServer.a(MinecraftServer.java:341) ~[Paper-1.12.2-b1616.jar:git-Paper-1616]
at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:289) ~[Paper-1.12.2-b1616.jar:git-Paper-1616]
at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:616) ~[Paper-1.12.2-b1616.jar:git-Paper-1616]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
Caused by: java.lang.ClassNotFoundException: com.zaxxer.hikari.HikariDataSource
at java.net.URLClassLoader.findClass(URLClassLoader.java:382) ~[?:1.8.0_212]
at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:156) ~[Paper-1.12.2-b1616.jar:git-Paper-1616]
at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:104) ~[Paper-1.12.2-b1616.jar:git-Paper-1616]
at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_212]
at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_212]
... 16 more`>

Do I have to use Spigot?

Thank you

**Comment by btk5h** [comment]
Do you get this error when not using Paper?

**Comment by Diamax10** [comment]
With spigot I have the same problem. For information I am in version 1.12.2

**Comment by btk5h** [comment]
Looks like just an issue with the uploaded artifact. Issue title was a little misleading. Fixed if you redownload.
