### ISSUE TITLE
Console error

### ISSUE THREAD

**Issue by tabels** [btk5h/skript-db#19]
I'm getting this error in the console:
`[00:03:43 INFO]: [skript-db] Enabling skript-db v0.2.0*
[00:03:43 ERROR]: Error occurred while enabling skript-db v0.2.0 (Is it up to date?)
java.lang.NoClassDefFoundError: com/zaxxer/hikari/HikariDataSource
at com.btk5h.skriptdb.skript.ExprDataSource.<clinit>(ExprDataSource.java:33) ~[?:?]
at java.lang.Class.forName0(Native Method) ~[?:1.8.0_212]
at java.lang.Class.forName(Class.java:348) ~[?:1.8.0_212]
at ch.njol.skript.SkriptAddon.loadClasses(SkriptAddon.java:108) ~[?:?]
at com.btk5h.skriptdb.SkriptDB.onEnable(SkriptDB.java:66) ~[?:?]
at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.14.3.jar:git-Paper-123]
at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:338) ~[patched_1.14.3.jar:git-Paper-123]
at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:419) ~[patched_1.14.3.jar:git-Paper-123]
at org.bukkit.craftbukkit.v1_14_R1.CraftServer.enablePlugin(CraftServer.java:466) ~[patched_1.14.3.jar:git-Paper-123]
at org.bukkit.craftbukkit.v1_14_R1.CraftServer.enablePlugins(CraftServer.java:380) ~[patched_1.14.3.jar:git-Paper-123]
at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:464) ~[patched_1.14.3.jar:git-Paper-123]
at net.minecraft.server.v1_14_R1.DedicatedServer.init(DedicatedServer.java:282) ~[patched_1.14.3.jar:git-Paper-123]
at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:859) ~[patched_1.14.3.jar:git-Paper-123]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
Caused by: java.lang.ClassNotFoundException: com.zaxxer.hikari.HikariDataSource
at java.net.URLClassLoader.findClass(URLClassLoader.java:382) ~[?:1.8.0_212]
at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:139) ~[patched_1.14.3.jar:git-Paper-123]
at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:85) ~[patched_1.14.3.jar:git-Paper-123]
at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_212]
at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_212]
... 14 more
[00:03:43 INFO]: [skript-db] Disabling skript-db v0.2.0`

I had it working before. It stopped working when I put `broadcast {sql}` out of curiosity into my code. Ever since I did that it just stopped working, I tried redownloading skript-db but it didn't help.

**Comment by tabels** [comment]
Just updated to skript-db-0.2.1 and the issue is fixed.
