### ISSUE TITLE
SQL Issues in 1.16.3 with execute unsafe

### ISSUE THREAD

**Issue by DevilishDante** [btk5h/skript-db#25]
Good morning, i have some issues in 1.16.3 before in 1.15.2 it worl correctly but in 1.16.3 when skript call : 

execute unsafe "SELECT * FROM `{@table_prefix}users` WHERE `{@table_prefix}users`.`pseudo` = '%player%'" in {SqlElyria} and store the result in {_siteReturn::*}

 i have this one in my console : 
```JAVA
[16:40:53] [pool-53-thread-1/WARN]: java.util.concurrent.CompletionException: java.util.MissingResourceException: Can't find bundle for base name com/sun/rowset/RowSetResourceBundle, locale fr_FR
[16:40:53] [pool-53-thread-1/WARN]:     at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:273)
[16:40:53] [pool-53-thread-1/WARN]:     at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:280)
[16:40:53] [pool-53-thread-1/WARN]:     at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1592)
[16:40:53] [pool-53-thread-1/WARN]:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[16:40:53] [pool-53-thread-1/WARN]:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[16:40:53] [pool-53-thread-1/WARN]:     at java.lang.Thread.run(Thread.java:748)
[16:40:53] [pool-53-thread-1/WARN]: Caused by: java.util.MissingResourceException: Can't find bundle for base name com/sun/rowset/RowSetResourceBundle, locale fr_FR
[16:40:53] [pool-53-thread-1/WARN]:     at java.util.ResourceBundle.throwMissingResourceException(ResourceBundle.java:1564)
[16:40:53] [pool-53-thread-1/WARN]:     at java.util.ResourceBundle.getBundleImpl(ResourceBundle.java:1387)
[16:40:53] [pool-53-thread-1/WARN]:     at java.util.ResourceBundle.getBundle(ResourceBundle.java:1082)
[16:40:53] [pool-53-thread-1/WARN]:     at com.sun.rowset.JdbcRowSetResourceBundle.<init>(JdbcRowSetResourceBundle.java:105)
[16:40:53] [pool-53-thread-1/WARN]:     at com.sun.rowset.JdbcRowSetResourceBundle.getJdbcRowSetResourceBundle(JdbcRowSetResourceBundle.java:124)
[16:40:53] [pool-53-thread-1/WARN]:     at com.sun.rowset.CachedRowSetImpl.<init>(CachedRowSetImpl.java:354)
[16:40:53] [pool-53-thread-1/WARN]:     at com.sun.rowset.RowSetFactoryImpl.createCachedRowSet(RowSetFactoryImpl.java:49)
[16:40:53] [pool-53-thread-1/WARN]:     at com.btk5h.skriptdb.skript.EffExecuteStatement.executeStatement(EffExecuteStatement.java:134)
[16:40:53] [pool-53-thread-1/WARN]:     at com.btk5h.skriptdb.skript.EffExecuteStatement.lambda$execute$0(EffExecuteStatement.java:94)
[16:40:53] [pool-53-thread-1/WARN]:     at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1590)
[16:40:53] [pool-53-thread-1/WARN]:     ... 3 more
>
```

and with take off "unsafe mention"
i've got that : 

 [Skript] Do not surround expressions with quotes!

How can i resolve that please? ty :o 
Skript version : 2.5.1 and 1.16.3 for mc version

**Comment by DevilishDante** [comment]
Nevermind, update SkMorkazz resolve the issues :o
